language: objective-c
matrix:
  include:
    - osx_image: xcode7.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
#  - pod spec lint
  - set -o pipefail
  - xcodebuild test -scheme Himotoki-Mac | xcpretty -c
  - xcodebuild test -scheme Himotoki-iOS -sdk iphonesimulator | xcpretty -c
  - xcodebuild test -scheme Himotoki-tvOS -sdk appletvsimulator | xcpretty -c
  - xcodebuild build -scheme Himotoki-watchOS -sdk watchsimulator | xcpretty -c
notifications:
  email: false
